name: Build Image

on:
  push:
    branches:
      - main
permissions:
  contents: write

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: sarocu/runrun

jobs:
  version:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.calver.outputs.release }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Calver Release
        uses: StephaneBour/actions-calver@master
        id: calver
        with:
          release_branch: main
          date_format: "%Y.%m"
          release: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - id: output-version
        run: echo "version=$(echo ${{ steps.calver.outputs.release }})" >> $GITHUB_OUTPUT
        shell: bash

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: version
    steps:
      - uses: actions/checkout@master
      - name: Compile
        id: compile
        uses: rust-build/rust-build.action@v1.4.4
        with:
          RUSTTARGET: x86_64-unknown-linux-musl
          UPLOAD_MODE: none
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: heynode-${{ needs.version.outputs.version }}
          path: |
            ${{ steps.compile.outputs.BUILT_ARCHIVE }}
            ${{ steps.compile.outputs.BUILT_CHECKSUM }}
